dist: trusty
language: node_js
node_js:
  - "6"
cache: false
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install: npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
after_script: greenkeeper-lockfile-upload
notifications:
  email: false
